# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "26b38db3da5235f34604ef2a02220f31"
name = "final"
application_url = "https://fireplace-around-introduction-complexity.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhook/orders/new"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_orders,read_products,read_script_tags,read_themes,write_pixels,write_script_tags,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://fireplace-around-introduction-complexity.trycloudflare.com"
]
