name = "avada-pixel"
type = "web_pixel_extension"
uid = "e94bf061-3fa8-8489-b2fd-4318db29edffdf0b6d8c"

runtime_context = "strict"

# This pixel will run without requiring specific privacy consent (essential for this tracking type)
[customer_privacy]
analytics = false
marketing = false
preferences = false
sale_of_data = "disabled"

[settings]
type = "object"

[settings.fields.appUrl]
name = "App URL"
description = "Backend URL for conversion API"
type = "single_line_text_field"
